package de.dimm.vsm.records;
// Generated 09.07.2009 10:42:43 by Hibernate Tools 3.2.1.GA

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;





/**
 * AccountConnector generated by hbm2java
 */
@Entity
public class AccountConnector  implements java.io.Serializable {

     static final long serialVersionUID = 1L;
     public static long FL_DISABLED = 0x01;
     public static long FL_SSL = 0x02;
     public static long FL_ALLOW_EMPTY_PWD = 0x04;

     public static String TY_LDAP = "ldap";
     public static String TY_AD = "ad";
     public static String TY_POP = "pop";
     public static String TY_IMAP = "imap";
     public static String TY_DBS = "dbs";


     @Id
     @GeneratedValue(strategy = GenerationType.AUTO)
     private long idx;
     
     private String type;
     private String ip;
     private Integer port;
     private String username;
     private String pwd;
     private String searchbase;
     private String searchattribute;
     private String mailattribute;
     private String domainlist;
     private String excludefilter;
     
     private long flags;
     
     private String ldapdomain;
     private String ldapfilter;
     private String groupIdentifier;


    public AccountConnector()
    {
    }

    @Override
    public String toString()
    {
        return getType() + ":" + getIp();
    }


	
    public AccountConnector(int id) {
        this.idx = id;
    }

    public AccountConnector( long id, String type, String ip, Integer port, String user, String pwd, String searchbase, long flags, String sa, String ma,
                                String domainlist, String excludefilter, String ldap_domain, String ldapfilter, String groupIdentifier )
    {
        this.idx = id;
        this.type = type;
        this.ip = ip;
        this.port = port;
        this.username = user;
        this.pwd = pwd;
        this.flags = flags;
        this.searchbase = searchbase;
        searchattribute = sa;
        mailattribute = ma;
        this.domainlist = domainlist;
        this.excludefilter = excludefilter;
        this.ldapdomain = ldap_domain;
        this.ldapfilter = ldapfilter;
        this.groupIdentifier = groupIdentifier;
    }

    public AccountConnector( AccountConnector a )
    {
        this.idx = a.idx;
        this.type = a.type;
        this.ip = a.ip;
        this.port = a.port;
        this.username = a.username;
        this.pwd = a.pwd;
        this.flags = a.flags;
        this.searchbase = a.searchbase;
        this.searchattribute = a.searchattribute;
        this.mailattribute = a.mailattribute;
        this.domainlist = a.domainlist;
        this.excludefilter = a.excludefilter;
        this.ldapdomain = a.ldapdomain;
        this.ldapfilter = a.ldapfilter;
        this.groupIdentifier = a.groupIdentifier;
    }
   
    public long getIdx() {
        return this.idx;
    }
    
    public void setIdx(long id) {
        this.idx = id;
    }
   
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Integer getPort() {
        return this.port;
    }
    
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * @return the user
     */
    public String getUsername()
    {
        return username;
    }

    /**
     * @param user the user to set
     */
    public void setUsername( String user )
    {
        this.username = user;
    }

    /**
     * @return the pwd
     */
    public String getPwd()
    {
        return pwd;
    }

    /**
     * @param pwd the pwd to set
     */
    public void setPwd( String pwd )
    {
        this.pwd = pwd;
    }

    /**
     * @return the flags
     */
    public long getFlags()
    {
        return flags;
    }

    /**
     * @param flags the flags to set
     */
    public void setFlags( long flags )
    {
        this.flags = flags;
    }

    public boolean isAllowEmptyPwd()
    {
        return ((this.flags & FL_ALLOW_EMPTY_PWD) == FL_ALLOW_EMPTY_PWD);
    }
    public boolean isSSL()
    {
        return ((this.flags & FL_SSL) == FL_SSL);
    }



    /**
     * @return the searchbase
     */
    public String getSearchbase()
    {
        return searchbase;
    }

    /**
     * @param searchbase the searchbase to set
     */
    public void setSearchbase( String searchbase )
    {
        this.searchbase = searchbase;
    }

    /**
     * @return the searchattribute
     */
    public String getSearchattribute()
    {
        return searchattribute;
    }

    /**
     * @param searchattribute the searchattribute to set
     */
    public void setSearchattribute( String searchattribute )
    {
        this.searchattribute = searchattribute;
    }

    /**
     * @return the mailattribute
     */
    public String getMailattribute()
    {
        if (mailattribute == null)
            return "";
        return mailattribute;
    }

    /**
     * @param mailattribute the mailattribute to set
     */
    public void setMailattribute( String mailattribute )
    {
        this.mailattribute = mailattribute;
    }

    /**
     * @return the domainlist
     */
    public String getDomainlist()
    {
        if (domainlist == null)
            return "";
        return domainlist;
    }

    /**
     * @param domainlist the domainlist to set
     */
    public void setDomainlist( String domainlist )
    {
        this.domainlist = domainlist;
    }

    /**
     * @return the excludefilter
     */
    public String getExcludefilter()
    {
        if (excludefilter == null)
            return "";
        return excludefilter;
    }

    /**
     * @param excludefilter the excludefilter to set
     */
    public void setExcludefilter( String excludefilter )
    {
        this.excludefilter = excludefilter;
    }

    public String getLdapdomain()
    {
        return ldapdomain;
    }

    public void setLdapdomain( String ldapdomain )
    {
        this.ldapdomain = ldapdomain;
    }

    public void setLdapfilter( String ldapfilter )
    {
        this.ldapfilter = ldapfilter;
    }

    public String getLdapfilter()
    {
        return ldapfilter;
    }

    public String getGroupIdentifier()
    {
        return groupIdentifier;
    }

    public void setGroupIdentifier( String groupIdentifier )
    {
        this.groupIdentifier = groupIdentifier;
    }





}


