package de.dimm.vsm.records;
// Generated 09.07.2009 10:42:43 by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;

/**
 * Role generated by hbm2java
 */
@Entity
public class MailGroup implements java.io.Serializable
{
    static final long serialVersionUID = 1L;
   

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long idx;

    private String name;
    private String opts;

    private String emailText;

    @OneToOne
    private SmtpLoginData smtpdata;

    public MailGroup()
    {
    }
   

    
 
  
    public long getIdx()
    {
        return this.idx;
    }

    public void setIdx( long id )
    {
        this.idx = id;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName( String name )
    {
        this.name = name;
    }

    public String getOpts()
    {
        return this.opts;
    }

    public void setOpts( String opts )
    {
        this.opts = opts;
    }

    public String getEmailText()
    {
        return emailText;
    }

    public void setEmailText( String emailText )
    {
        this.emailText = emailText;
    }
    public List<String> getEmails()
    {
        return getEmails(emailText);
    }
    public static List<String> getEmails(String txt)
    {
        List<String> ret = new ArrayList<String>();
        if (txt == null || txt.isEmpty())
            return ret;

        String s = txt.replace(',', ' ');

        String[] arr = s.split(" ");
        for (int i = 0; i < arr.length; i++)
        {
            String string = arr[i];
            if (string != null && !string.isEmpty())
                ret.add(string);
        }
        return ret;
    }
    public void setEmails(List<String> l)
    {
        StringBuilder sb = new StringBuilder();

        for (int i = 0; i < l.size(); i++)
        {
            String string = l.get(i);
            if (sb.length() > 0)
                sb.append(" ");
            sb.append(string);
        }
        emailText = sb.toString();
    }

    @Override
    public String toString()
    {
        return name;
    }

    public SmtpLoginData getSmtpdata()
    {
        return smtpdata;
    }

    public void setSmtpdata( SmtpLoginData smtpdata )
    {
        this.smtpdata = smtpdata;
    }

    

    
        
}
