package de.dimm.vsm.records;
// Generated 09.07.2009 10:42:43 by Hibernate Tools 3.2.1.GA

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;


/**
 * HotfolderExclude generated by hbm2java
 */
@Entity
public class RoleOption implements java.io.Serializable
{
    static final long serialVersionUID = 1L;

    public static final String RL_ALLOW_VIEW_PARAM = "viewp";
    public static final String RL_ALLOW_EDIT_PARAM = "editp";
    public static final String RL_ADMIN = "admin";

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long idx;

    @ManyToOne
    private Role role;
    private String token;
    private long flags;

    public RoleOption()
    {
    }

    @Override
    public String toString()
    {
        return token;
    }


    public RoleOption( int id )
    {
        this.idx = id;
    }

    public RoleOption( int id, Role r, String token, int flags )
    {
        this.idx = id;
        this.role = r;
        this.token = token;
        this.flags = flags;
    }

    public long getIdx()
    {
        return this.idx;
    }

    public void setIdx( long id )
    {
        this.idx = id;
    }

    public Role getRole()
    {
        return this.role;
    }

    public void setRole( Role role )
    {
        this.role = role;
    }

    public String getToken()
    {
        return this.token;
    }

    public void setToken( String token )
    {
        this.token = token;
    }

    public long getFlags()
    {
        return this.flags;
    }

    public void setFlags( long flags )
    {
        this.flags = flags;
    }
}
