package de.dimm.vsm.records;
// Generated 09.07.2009 10:42:43 by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Role generated by hbm2java
 */
@Entity
public class SmtpLoginData implements java.io.Serializable
{
    static final long serialVersionUID = 1L;
   

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long idx;

    private String name;
    private String serverip;
    int serverport;

    private String smtpfrom;
    private String username;
    private String userpwd;
    boolean ssl;
    boolean tls;

   

    public SmtpLoginData()
    {
    }
   

    
 
  
    public long getIdx()
    {
        return this.idx;
    }

    public void setIdx( long id )
    {
        this.idx = id;
    }

    public String getName()
    {
        return this.name;
    }

    public void setName( String name )
    {
        this.name = name;
    }   

    @Override
    public String toString()
    {
        return name;
    }

    public String getServerip()
    {
        return serverip;
    }

    public int getServerport()
    {
        return serverport;
    }

    public String getSmtpfrom()
    {
        return smtpfrom;
    }

    public String getUsername()
    {
        return username;
    }

    public String getUserpwd()
    {
        return userpwd;
    }

    public void setServerip( String serverip )
    {
        this.serverip = serverip;
    }

    public void setServerport( int serverport )
    {
        this.serverport = serverport;
    }

    public void setSmtpfrom( String smtpfrom )
    {
        this.smtpfrom = smtpfrom;
    }

    public void setSsl( boolean ssl )
    {
        this.ssl = ssl;
    }

    public void setTls( boolean tls )
    {
        this.tls = tls;
    }

    public void setUsername( String username )
    {
        this.username = username;
    }

    public void setUserpwd( String userpwd )
    {
        this.userpwd = userpwd;
    }

    public boolean isSsl()
    {
        return ssl;
    }

    public boolean isTls()
    {
        return tls;
    }

    


    
        
}
